### PR TITLE
Add support for playing from the VOD Catalog

### LINKED ISSUE #51: Add support for the content catalog
Some subscription allow to stream movies or series from a catalog. It would be nice to be able to stream these from Kodi also.

### PR DESCRIPTION
**Pull request by michaelarnauts**
* Add supports for playing from the VOD Catalog
* Use current API version when logging in
* Refactor code

Fixes #51 

Untested, since I don't have a VOD catalog in my subscription.

### CODE REVIEW

**Comment by michaelarnauts** [comment]
[plugin.video.focussat-1.0.5.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7965910/plugin.video.focussat-1.0.5.zip)
[plugin.video.focussat-1.0.5+matrix.1.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7965911/plugin.video.focussat-1.0.5%2Bmatrix.1.zip)
[plugin.video.hdaustria-1.0.5.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7965912/plugin.video.hdaustria-1.0.5.zip)
[plugin.video.hdaustria-1.0.5+matrix.1.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7965913/plugin.video.hdaustria-1.0.5%2Bmatrix.1.zip)
[plugin.video.tvvlaanderen-1.0.5.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7965914/plugin.video.tvvlaanderen-1.0.5.zip)
[plugin.video.tvvlaanderen-1.0.5+matrix.1.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7965915/plugin.video.tvvlaanderen-1.0.5%2Bmatrix.1.zip)

@bananenfisch I think you have VOD available in your subscription? Can you try this out? Also, are you interested in helping out with this add-on? Feel free to send me an email, so I can add you to our Slack channel.

**Comment by bananenfisch** [comment]
Hi, yes i have VOD content. Sorry, little busy this week, but i will test it next days!

**Comment by marnux** [comment]
My parents got a subscription with VOD and wanted to access it on Kodi. I had Kodi running the vtm go, go play and vrt nu plugins, before they ditched the regular tv subscription. I will be installing the updated addon from this branch, when i get a chance. I'll let you know how it works. Would be nice to have it generally available, if it turns out stable.

**Comment by marnux** [comment]
So far the experience with the VOD related stuff seems to be ok, according to my parents. They just miss an easy seperation between the movies and series that are available. If you would be able to split them, you could house them in the video and series subsections of the default kodi menu and provide easier access.

**Pull request merged**
