### PR TITLE
Add support for Focus Sat in Romania

### LINKED ISSUE #41: Focussat Romania
Hi. Can you add Focussat Romania?  The correct domain is domain='livetv.focussat.ro' and env seems to be env='m7cz2iphone'.
Thank you

### PR DESCRIPTION
**Pull request by michaelarnauts**
Fixes #41

### CODE REVIEW

**Comment by michaelarnauts** [comment]
[plugin.video.focussat-1.0.4.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7887712/plugin.video.focussat-1.0.4.zip)
[plugin.video.focussat-1.0.4+matrix.1.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7887713/plugin.video.focussat-1.0.4%2Bmatrix.1.zip)

**Comment by derzis** [comment]
Not working. I tested on Kodi 18.9 in Windows 10 and Kodi 19.3 in Manjaro. The error encountered is "An error ocurred while autheticating:{error}"

**Comment by michaelarnauts** [comment]
@derzis it should work now. The env was `m7cziphone`, and the authentication form was a bit different.

Could you test again? I've uploaded new zips in the comment above (https://github.com/add-ons/plugin.video.tvvlaanderen/pull/42#issuecomment-1014648483)

**Comment by derzis** [comment]
It's working. I tested on Kodi 19.3 in Manjaro Kde. Thank you
P.S. I will send you romanian translation through mail

**Pull request merged**
